version: '3.8'
services:
  usuario:
    build:
      context: ../usuario
    ports:
      - "8083:8080"
    volumes:
      - ./wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=usuario
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@fullstackusuario_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=FullStack-001
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend

networks:
  backend:
    driver: bridge